worker_processes  1;

error_log  logs/error.log info;
pid        logs/nginx.pid;

events {
    worker_connections  16;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout  65;

    include conf.d/*.conf;
}
